import { Metadata } from "next";
import Cart from "./cart";
export const metadata: Metadata = {
   title: 'Корзина',
   description: 'Generated by create next app',
   icons: {
      icon: '/cart.ico',
   },
};
export default function CartPage() {
   return <>
      <Cart />
   </>
}